config/routes.rb
Rails.application.routes.draw do
  root "traders#index"

  # Session routes
  get "/signin" => "sessions#signin", as: :signin_page
  get "/signup" => "sessions#signup", as: :signup_page
  get "/userinfo" => "sessions#userinfo", as: :userinfo
  post "/signin" => "sessions#new_session", as: :new_session
  post "/signup" => "sessions#new_account", as: :new_account
  post "/userinfo" => "sessions#new_userinfo", as: :new_userinfo
  post "/signout" => "sessions#signout", as: :signout

  # Admin Dashboard
  get "/admin" => "admins#index"
  # --Pages
  post "/admin" => "admins#homepage"
  post "/admin/userpage" => "admins#userpage"
  # --- Users
  post "/admin/user" => "admins#edit_user", as: :edit_user
  patch "/admin/user" => "admins#update_user", as: :update_user
  post "/admin/user/show" => "admins#show_user"
  post "/admin/user/new" => "admins#new_user", as: :new_user
  post "/admin/user/create" => "admins#create_user", as: :create_user
  post "/admin/user/activate" => "admins#activate_user", as: :activate_user
  post "/admin/user/search" => "admins#search_user"
  # ---- Users View
  post "/admin/user/waiting" => "admins#waiting_list"
  post "/admin/user/active" => "admins#active_users"
  post "/admin/user/filter_order" => "admins#filter_order"

  # Trader Homepage
  get "/home" => "traders#index"
  get "/pending" => "traders#pending", as: :pending_page
  # -- Pages
  get "/deposit" => "traders#deposit"
  get "/buy-sell" => "traders#buysell"
  get "/market" => "traders#market"
  get "/profile" => "traders#profile"
  get "/transaction" => "traders#transaction"
  # --- btn actions
  post "/deposit/addbalance" => "traders#add_balance"
  post "/buy-sell" => "traders#user_buysell"
  post "/transaction" => "traders#filter_transaction"

end

app/views/admins/_default.html.erb
<div class="flex flex-col text-white">
  <span>Active Users = 0</span>
  <span>Newly Created Users = 0</span>
</div>

app/views/admins/_sidepanel.html.erb
<%= turbo_stream.prepend "sidepanel" do %>
  <span class="text-xl font-bold mb-4">Sidepanel</span>
  <div class="flex gap-2 items-center">
    <span class="w-[20px] text-center"><i class="fa-solid fa-house-chimney"></i></i></span>
    <%= button_to "Home", admin_path %>
  </div>

  <div class="flex flex-col">
    <input type="checkbox" id="useractions" class="peer/useractions hidden">
    <label for="useractions" class="peer/useractions flex gap-2 select-none cursor-pointer">
      <span><i class="fa-solid fa-user-group"></i></span>
      Users
      <span class="ml-auto"><i class="fa-solid fa-chevron-down"></i></span>
    </label>

    <div class="pl-8 hidden peer-checked/useractions:block">

      <div class="flex gap-2">
        <%= button_to "List of Users", admin_userpage_path, data: { turbo: true } %>
      </div>

      <div class="flex gap-2">
        <%= button_to "Create New User", new_user_path, data: { turbo: true } %>
      </div>

      <div class="flex gap-2">
        <%= button_to "Online Users", admin_user_active_path, data: { turbo: true } %>
      </div>

      <div class="flex gap-2">
        <%= button_to "Waiting Users",  admin_user_waiting_path, data: { turbo: true } %>
      </div>
    </div>
  </div>

  <div class="flex gap-2 items-center">
    <span class="w-[20px]"><i class="fa-solid fa-envelope"></i></i></span>
    <span>Messages</span>
  </div>

  <div class="flex gap-2 items-center">
    <i class="fa-solid fa-door-open"></i>
    <%= button_to "Logout", signout_path, data: { turbo: true }, class: "text-white h-[40px] w-[40px] bg-[#0b0f16]" %>
  </div>

  <!-- temporary hidden -->
  <div class="mt-auto hidden">
    <input type="checkbox" id="sidepanel-2" class="peer/sidepanel-2">
    <label for="sidepanel-2" class="peer/sidepanel-2 select-none cursor-pointer
    text-white ">
      Minimize Menu
    </label>
    <span class="peer-checked/sidepanel-2:hidden block">to be hidden</span>
  </div>
<% end %>

app/views/admins/_userlist.html.erb
<div class="user-list">
  <span class="text-white">
    <%= index + 1 %>
  </span>
  
  <span class="flex text-white">
    <div class="h-[25px] w-[25px] flex justify-center items-center rounded-full border-white border-[1px]">
      <i class="fa-solid fa-user "></i>
    </div>
    <div class="ml-2">
      <%= user.lname %>, <%= user.fname %> <%= user.mname %>
    </div>
  </span>
  
  <span class="text-white">
    <%= user.email %>
  </span>
  
  <span class="text-white">
    <%= user.status %>
  </span>

  <span class="text-white border-r-[1px] border-[#f890e7]">
    <%= user.created_at %>
  </span>

  <div class="flex gap-4 ml-2 border-r-[1px] border-[#f890e7]">
    <%= link_to "view", "", class: "text-white" %>

    <%= button_to "edit", edit_user_path(email: user.email), 
    class: "text-white" %>

    <%= button_to "activate", activate_user_path(email: user.email), class: "text-white" %>
  </div>
</div>

app/views/admins/homepage.turbo_stream.erb
<%= turbo_stream.update "dashboard" do %>
  <%= render "default" %>
<%end%>

app/views/admins/index.html.erb
<div class="flex h-[100%] w-[100%]">
  
  <div id="sidepanel" class="flex flex-col bg-[#0b0f16] text-white text-lg
    p-4 min-w-[220px]">
    <%= render partial: "sidepanel" %>
  </div>

  <%= turbo_frame_tag "dashboard", class: "pt-4 w-full px-10" do %>
    <%= render "default" %>
  <% end %>    
  
</div>

app/views/admins/newuser.html.erb
<%= form_with(scope: @user, url: new_userinfo_path, html: { class: "w-full max-w-sm mx-auto" }) do |form| %>
  <%= form.hidden_field( :id, :value => params[:id])%>
  <div class="mb-4">
    <%=form.label "First Name", class: "form-label"%>
    <%=form.text_field :fname, class: "form-inputbox"%>
  </div>

  <div class="mb-4">
    <%=form.label "Middle Nane", class: "form-label"%>
    <%=form.text_field :mname, class: "form-inputbox"%>
  </div>  
  
  <div class="mb-4">
    <%=form.label "Last Name", class: "form-label"%>
    <%=form.text_field :lname, class: "form-inputbox"%>
  </div>

  <div class="mb-4">
    <%=form.label "Contacts", class: "form-label"%>
    <%=form.text_field :contacts, class: "form-inputbox"%>
  </div>

  <div class="mb-4">
    <%=form.label "Address", class: "form-label"%>
    <%=form.text_field :address, class: "form-inputbox"%>
  </div>  

  <div class="flex items-center justify-between">
    <%= form.submit "Signup", class: "btn-primary" %>
  </div>
<%end%>

app/views/admins/userpage.turbo_stream.erb
<%= turbo_stream.update "dashboard" do %>
  <%= render "admins/users/userlist" %>
<% end %>