config/routes.rb
Rails.application.routes.draw do
  root "traders#index"

  # Session routes
  get "/signin" => "sessions#signin", as: :signin_page
  get "/signup" => "sessions#signup", as: :signup_page
  get "/userinfo" => "sessions#userinfo", as: :userinfo
  post "/signin" => "sessions#new_session", as: :new_session
  post "/signup" => "sessions#new_account", as: :new_account
  post "/userinfo" => "sessions#new_userinfo", as: :new_userinfo
  post "/signout" => "sessions#signout", as: :signout

  # Admin Dashboard
  get "/admin" => "admins#index"
  # --Pages
  post "/admin" => "admins#homepage"
  post "/admin/userpage" => "admins#userpage"
  # --- Users
  post "/admin/user" => "admins#edit_user", as: :edit_user
  patch "/admin/user" => "admins#update_user", as: :update_user
  post "/admin/user/show" => "admins#show_user"
  post "/admin/user/new" => "admins#new_user", as: :new_user
  post "/admin/user/create" => "admins#create_user", as: :create_user
  post "/admin/user/activate" => "admins#activate_user", as: :activate_user
  post "/admin/user/search" => "admins#search_user"
  # ---- Users View
  post "/admin/user/waiting" => "admins#waiting_list"
  post "/admin/user/active" => "admins#active_users"
  post "/admin/user/filter_order" => "admins#filter_order"

  # Trader Homepage
  get "/home" => "traders#index"
  get "/pending" => "traders#pending", as: :pending_page
  # -- Pages
  get "/deposit" => "traders#deposit"
  get "/buy-sell" => "traders#buysell"
  get "/market" => "traders#market"
  get "/profile" => "traders#profile"
  get "/transaction" => "traders#transaction"
  # --- btn actions
  post "/deposit/addbalance" => "traders#add_balance"
  post "/buy-sell" => "traders#user_buysell"
  post "/transaction" => "traders#filter_transaction"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :require_user
  before_action :initialize_iex_client
  before_action :initialize_stocks_master
  before_action :company_dashboard

  helper_method :get_logo, :get_quote, :check_url, :check_quote

  def index
    
    response = Faraday.get('https://cloud.iexapis.com/v1/stock/market/list/mostactive?token=pk_06f0670b09884fe5aa66d394e4263f00') 
    @most_active = JSON.parse(response.body)   

    response = Faraday.get('https://cloud.iexapis.com/v1/stock/market/batch?types=news&range=1m&last=5&token=pk_06f0670b09884fe5aa66d394e4263f00')
    @news = JSON.parse(response.body)

    userauth = Authentication.find_by(token: session[:gen_token])
    pending = userauth.user.status === "pending" ? true : false

    if pending 
      redirect_to pending_page_path
    end
  end

  def pending
    random_emoji = ["(·.·)", "(·_·)", "(>_<)","(o_o)", "(^_^)b","(o^^)o","(^-^*)","(^Д^)","(;-;)","┬─┬ノ( º _ ºノ)", "(╯°□°)╯︵ ┻━┻","(┛ಠ_ಠ)┛彡┻━┻","┳━┳ ヽ(ಠل͜ಠ)ﾉ","(┛◉Д◉)┛彡┻━┻"]

    @display_emoji = random_emoji.sample
  end

  def buysell
    @paginated_items = Kaminari.paginate_array($stocks_master).page(params[:page]).per(10)
  end

  def market

    response = Faraday.get('https://cloud.iexapis.com/v1//stock/market/list/mostactive?token=pk_06f0670b09884fe5aa66d394e4263f00&listLimit=5')
    @mostactive = JSON.parse(response.body)

    response = Faraday.get('https://cloud.iexapis.com/v1//stock/market/list/gainers?token=pk_06f0670b09884fe5aa66d394e4263f00&listLimit=5')
    @gainers = JSON.parse(response.body)

    response = Faraday.get('https://cloud.iexapis.com/v1//stock/market/list/losers?token=pk_06f0670b09884fe5aa66d394e4263f00&listLimit=5')
    @losers = JSON.parse(response.body)

  end

  def trade
  end

  def profile 

    @user_details = User.find(current_user.id)
    @latest_login = @user_details.logins.last
    @auth_lvl = @user_details.authentication
    @portfolio= Transaction::Portfolio.display(current_user.id)
  end

  def transaction
    @user_history = Transaction::History.show(current_user.id, params[:kind])    
  end

  def filter_transaction
    @user_history = Transaction::History.show(current_user.id, params[:kind])
    respond_to do |format|
      format.turbo_stream{
        render turbo_stream: turbo_stream.update("transaction_history", partial: "home/user/transaction", locals:{
          user_history: @user_history
        })
      }
    end    
  end

  # ------ balance transactions ------

  def add_balance
    Transaction::Generator.deposit(current_user.id, params[:amount])
    TransactionRepository.record_transaction(current_user.id, params)
  end

  def user_buysell
    # --- params[:commit] Buy or Sell
    case params[:commit]
    when "Buy"
      Transaction::Generator.buy(current_user.id, params)
    when "Sell"
      Transaction::Generator.sell(current_user.id, params)
    end
    user = User.find(current_user.id)   

    symbol = params[:symbol] ? params[:symbol] : 'TSLA'

    onhand = Transaction::Inventory.stock_count(current_user.id, symbol)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: [
        turbo_stream.update("balance", number_to_currency(user.balance)),
        turbo_stream.update("onhand", onhand)
      ]}
    end
  end

  # -------------------- Testing Purpose Only
  def sample 

    # configure mailslurp client globally with API key (or pass each controller a client instance)
    MailSlurpClient.configure do |config|
        config.api_key['x-api-key'] = "967f6dfe6944c47bb2d3b247282d34960a8480c35a096053f569378db54abb4f"
    end
    
    inbox_controller = MailSlurpClient::InboxControllerApi.new
    
    #inbox1 = inbox_controller.create_inbox_with_options({ inboxType: 'SMTP_INBOX' })
    #inbox2 = inbox_controller.create_inbox

    
    smtp_access = inbox_controller.get_imap_smtp_access({ inbox_id: "800226e1-87f4-4b5f-8f89-9b609f0c1bb1" })

    message = <<~MESSAGE_END
      From: "800226e1-87f4-4b5f-8f89-9b609f0c1bb1@mailslurp.mx"
      To: "miamitrades@zohomail.com"
      Subject: Testing lang

      This is a test galing sa mailslurp
    MESSAGE_END

    # configure NET SMTP with plain auth
    Net::SMTP.start(smtp_access.smtp_server_host, smtp_access.smtp_server_port, 'greeting.your.domain',
                smtp_access.smtp_username, smtp_access.smtp_password, :plain) do |smtp|
      # send email
      smtp.send_message message, "800226e1-87f4-4b5f-8f89-9b609f0c1bb1@mailslurp.mx", "miamitrades@zohomail.com"
    end 
  end

  private
# ---------- Helpers ----------
  def get_logo(stock_symbol)
    @iex_client.logo(stock_symbol)['url']
  end

  def get_quote(stock_symbol)
    @iex_client.quote(stock_symbol)
  end 

  def check_url(stock_symbol)
    if newarray = $stocks_master.find { |item| item['symbol'] == stock_symbol }
      if newarray['url']
        newarray['url']
      else
        newarray['url'] = @iex_client.logo(stock_symbol)['url']
        $stocks_master.find { |item| item['symbol'] == stock_symbol ? item.replace(newarray) : '' }
        File.write('./app/helpers/stock_master.json', JSON.dump($stocks_master))
        newarray['url']
      end
    end
  end

  def check_quote(stock_symbol)
    if newarray = $stocks_master.find { |item| item['symbol'] == stock_symbol }
      if newarray['quote']
        newarray['quote']
      else
        newarray['quote'] = @iex_client.quote(stock_symbol)
        $stocks_master.find { |item| item['symbol'] == stock_symbol ? item.replace(newarray) : '' }
        File.write('./app/helpers/stock_master.json', JSON.dump($stocks_master))
        newarray['quote']
      end
    end
  end
#-----------------------------
  def company_dashboard
    symbol = params[:symbol] ? params[:symbol] : 'TSLA'
    @quote = @iex_client.quote(symbol)
    @logo = @iex_client.logo(symbol)['url']
    # @chart_data = get_chart_data(symbol)
    @chart_data = Stock::Chart.candle(symbol)
    @balance = TransactionRepository.show_balance(current_user.id)
    @onhand = Transaction::Inventory.stock_count(current_user.id, symbol)
  end

  def get_chart_data(stock_symbol)
    # puts stock_symbol    
    chart = @iex_client.chart(stock_symbol)
    chart_arr = chart.reduce([]) { |init, curr| 
      init.push([curr['label'], curr['open'], curr['close'], curr['high'], curr['low']]);     
    }.inject({}) do |res, k|
        res[k[0]] = k[1..-1]
        res
      end
  end
  
end

app/views/home/buysell.html.erb
<%= render "navbar" %>

<div class="flex flex-col items-center pt-8">
  <div class="flex flex-col mb-8">
    <div id="buysell">
      <%= render "home/user/form_buysell" %>
    </div>

    <div id="candlestick" class="bg-[#0b0f16] rounded-xl p-2">
      <%= render "home/components/candlestick_chart" %>
    </div>
  </div>
  
  <div class="flex flex-col gap-[2px]">

    <div>
    
    </div>

    <div class="mb-12">
      <div class="mb-2">
        <div class="flex text-gray-500">
          <div class="flex flex-1 gap-2 min-w-[300px]">
            <span class="w-[60px]"></span>
            <span class="">Name</span>
          </div>
          <span class="flex-1 text-center min-w-[100px] self-center">Currency</span>
          <span class="flex-1 text-center min-w-[100px] self-center">Change</span>
          <span class="flex-1 text-center min-w-[100px] self-center">Price</span>
          <span class="flex-1 text-right min-w-[150px] self-center">Avg. Vol</span>
          <span class="flex-1 text-right min-w-[200px] self-center mr-5">Market Cap</span>
        </div>

        <% @paginated_items.each do |item| %>
          <%= render "home/components/paginated_frame", 
            item: item, 
            url: check_url(item['symbol']), 
            quote: check_quote(item['symbol'])
          %>
        <% end %>
      </div>
      <%= paginate @paginated_items %>
    </div>
  </div>
</div>

app/views/home/deposit.html.erb
<%= render "navbar" %>

<div class="flex justify-center items-center pt-12">

  <div>
    <%= render "/home/user/form_deposit" %>
  </div>

</div>

app/views/home/index.html.erb
<%= render "navbar" %>

<div class="flex flex-col mx-[40px]">

  <div id="container" class="flex flex-col justify-center items-center px-8">

    <%= turbo_frame_tag "mainview", class: "flex flex-col justify-center items-center 
    h-[400px] w-full min-w-[970px] bg-[#0b0f16] mt-8 rounded-md select-none" do %>
      <div class="min-w-[965px] flex flex-col relative">
        <div class="w-[100px] h-[100px] -translate-y-[80px] text-[#151b29] absolute">
          <span class="absolute translate-x-8 translate-y-12 rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute translate-x-12 translate-y-4 rotate-[30deg] text-[30px]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute translate-x-[55px] -translate-y-2 -rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute translate-x-[100px] translate-y-6 -rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
        </div>
        <span class="text-white text-4xl font-extrabold">Maximize Your Trading Power </span>
        <span class="text-white mb-8 text-2xl">Load Your Account Balance Today</span>
        
        <div class="self-start">
          <%= button_to "Load Account", home_deposit_path, method: :get, data: {turbo: false}, class: "btn-primary" %>
        </div>

        <div class="w-[400px] h-[400px] text-[#151b29] absolute right-0 -translate-y-32">
          <span class="absolute translate-x-10 text-[300px] rotate-[30deg]"> <i class="fa-solid fa-gem"></i></span>
          <span class="absolute -translate-x-[100px] translate-y-[140px] text-[200px] -rotate-[30deg]"> <i class="fa-solid fa-gem"></i></span>
          <span class="absolute text-[30px] translate-y-[120px] -rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute translate-x-8 translate-y-[120px] rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute translate-y-[100px] -rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
          <span class="absolute -translate-x-6 translate-y-[140px] -rotate-[30deg]"><i class="fa-solid fa-diamond"></i></span>
        </div>
        
      </div>
    <% end %>

    <%= turbo_frame_tag "news", class: "w-[965px] pt-12" do %>
      <div class="self-start mb-4 p-4 flex items-center">
        <span class="text-4xl text-white font-bold">Latest News</span>
      </div>

      <div class="flex flex-col gap-[1px] max-h-[250px] overflow-auto">
        <% @news["news"].each do |news| %>
          <%= render "home/lists/latestnews", news: news %>
        <% end %>
      </div>

    <% end %>
    
    <%= turbo_frame_tag "mostpopular", class: "pt-12" do %>
      <div class="self-start mb-4 p-4 flex items-center">
        <span class="text-4xl text-white font-bold ">Most active companies</span>
        <span class="text-gray-500 ml-auto cursor-pointer transition-all duration-100 ease-in hover:text-[#03e9f4] hover:underline">View more markets</span>
      </div>
      <div class="flex text-gray-500 p-4">
        <span class="min-w-[320px]">Name</span>
        <span class="min-w-[200px] text-center">Latest Price</span>
        <span class="min-w-[200px] text-center">Change</span>
        <span class="min-w-[200px] text-right">Market Cap</span>
      </div>

      <% @most_active.each do |data| %>
        <%= render "home/lists/mostpopular", company: data %>
      <% end %>
    <% end %>
    
  </div>

</div>

app/views/home/market.html.erb
<%= render "navbar" %>

<div class="flex flex-col mx-[40px]">

  <div class="flex gap-8 justify-center pt-12">
    <%= turbo_frame_tag "top_mostactive" do %>
      <% @mostactive.each do |comp| %>
        <%= render "home/lists/top5", company: comp %>
      <% end %>
    <% end %>

    <%= turbo_frame_tag "top_gainers" do %>
      <% @gainers.each do |comp| %>
        <%= render "home/lists/top5", company: comp %>
      <% end %>
    <% end %>

    <%= turbo_frame_tag "top_losers" do %>
      <% @losers.each do |comp| %>
        <%= render "home/lists/top5", company: comp %>
      <% end %>
    <% end %>

  </div>

  <%= @testingmarket %>

</div>

app/views/home/transaction.html.erb
<%= render "navbar" %>
<div style="color: #ccc">
  <div class="flex container">
    <div class="flex flex-col m-8 " style="width: 15%">
      <div class="widget-container">
        <div class="transaction-widget rounded-lg  text-gray-500 text-2xl  items-center p-2 my-2">
          Transaction Filter
        </div>
        <div class="transaction-widget rounded-lg text-gray-500 justify-center p-2 my-2 text-xl">
          <%= button_to "Buy", home_transaction_path(:kind => "Buy"), :class => "widget-button container" %>
          <%= button_to "Sell", home_transaction_path(:kind => "Sell"), :class => "widget-button container" %>
          <%= button_to "Deposit", home_transaction_path(:kind => "Deposit"), :class => "widget-button container" %>
          <%= button_to "All", home_transaction_path(:kind => "All"), :class => "widget-button container" %>
        </div>
      </div>
    </div>
    <div class="container">
      <turbo-frame id="transaction_history" class="flex flex-col gap-4 min-w-[500px] px-2 m-8">    
        <%= render "home/user/transaction" %>
      </turbo-frame>
    </div>
  </div>
</div>
  
   
  