config/routes.rb
Rails.application.routes.draw do
  root "traders#index"

  # Session routes
  get "/signin" => "sessions#signin", as: :signin_page
  get "/signup" => "sessions#signup", as: :signup_page
  get "/userinfo" => "sessions#userinfo", as: :userinfo
  post "/signin" => "sessions#new_session", as: :new_session
  post "/signup" => "sessions#new_account", as: :new_account
  post "/userinfo" => "sessions#new_userinfo", as: :new_userinfo
  post "/signout" => "sessions#signout", as: :signout

  # Admin Dashboard
  get "/admin" => "admins#index"
  # --Pages
  post "/admin" => "admins#homepage"
  post "/admin/userpage" => "admins#userpage"
  # --- Users
  post "/admin/user" => "admins#edit_user", as: :edit_user
  patch "/admin/user" => "admins#update_user", as: :update_user
  post "/admin/user/show" => "admins#show_user"
  post "/admin/user/new" => "admins#new_user", as: :new_user
  post "/admin/user/create" => "admins#create_user", as: :create_user
  post "/admin/user/activate" => "admins#activate_user", as: :activate_user
  post "/admin/user/search" => "admins#search_user"
  # ---- Users View
  post "/admin/user/waiting" => "admins#waiting_list"
  post "/admin/user/active" => "admins#active_users"
  post "/admin/user/filter_order" => "admins#filter_order"

  # Trader Homepage
  get "/home" => "traders#index"
  get "/pending" => "traders#pending", as: :pending_page
  # -- Pages
  get "/deposit" => "traders#deposit"
  get "/buy-sell" => "traders#buysell"
  get "/market" => "traders#market"
  get "/profile" => "traders#profile"
  get "/transaction" => "traders#transaction"
  # --- btn actions
  post "/deposit/addbalance" => "traders#add_balance"
  post "/buy-sell" => "traders#user_buysell"
  post "/transaction" => "traders#filter_transaction"

end

app/models/user.rb
class User < ApplicationRecord
  has_one :authentication
  has_many :logins
  has_many :transactions

  before_validation :convert_downcase
  validates :email, uniqueness: true
  validates :email, presence: true

  # user_level { 1 = trader, 2 = admin }

  def self.create_user(params)
    new(
      email: params[:email],
      status: "pending",
    ).save
    Authentication.signup(params)
  end

  def self.admin_create_user(params)
    new(params).save
    user = User.find_by(email: params[:email])
    Authentication.create(user_id: user.id, 
      username: SecureRandom.hex(3), 
      password: SecureRandom.hex(4), 
      user_level: 1).save
  end
  
  def self.signup(user_params)
    user = find(user_params[:id])
    user.update( fname: user_params[:fname],
      mname: user_params[:mname],
      lname: user_params[:lname],
      contacts: user_params[:contacts],
      address: user_params[:address],
    )
  end

  def self.patch(user_params)
    user = find_by(email: user_params[:email])
    user.update(email: user_params[:email],
      fname: user_params[:fname],
      mname: user_params[:mname],
      lname: user_params[:lname],
      contacts: user_params[:contacts],
      address: user_params[:address],
    )
  end

  def convert_downcase
    self.email.downcase! 
    self.fname ? self.fname.downcase! : ""
    self.mname ? self.mname.downcase! : ""
    self.lname ? self.lname.downcase! : ""
    self.address ? self.address.downcase! : ""
  end

end

app/models/user/admin.rb
class User
  class Admin
    def self.user_list(list_type)
      case list_type
      when "userpage"
        @user = User.order(created_at: :desc)
      when "waiting_list"
        @user = User.order(created_at: :desc).where(status: "pending")
      when "active_users"
        @user = User.joins(:authentication).where( authentication: { is_active: true })
      end
    end
  end
end

app/views/admins/users/_edit_user.html.erb
<%= turbo_stream.update "dashboard" do %>
<%= form_with(scope: @user, url: update_user_path, method: :patch, html: { class: "form-1" }) do |form| %>

  <div class="p-4">
    <span class="text-white text-4xl font-bold">Trader Details</span>
  </div>

  <div class="flex flex-col p-6">
    <div class="mb-4">
      <%=form.label "Email", class: "form-label"%>
      <%=form.text_field :email, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "First Name", class: "form-label"%>
      <%=form.text_field :fname, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "Middle Name", class: "form-label"%>
      <%=form.text_field :mname, class: "form-inputbox"%>
    </div>  
    
    <div class="mb-4">
      <%=form.label "Last Name", class: "form-label"%>
      <%=form.text_field :lname, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "Contacts", class: "form-label"%>
      <%=form.text_field :contacts, class: "form-inputbox"%>
    </div>

    <div class="mb-8">
      <%=form.label "Address", class: "form-label"%>
      <%=form.text_field :address, class: "form-inputbox"%>
    </div>  

    <div class="flex items-center justify-between self-center mb-4">
      <%= form.submit "Update",class: "btn-primary" %>
    </div>
  </div>

<%end%>
<% end %>

app/views/admins/users/_new_user.html.erb
<%= form_with(scope: @user, url: create_user_path, html: { class: "form-1" }) do |form| %>

  <div class="p-4">
    <span class="text-white text-4xl font-bold">Add New Trader</span>
  </div>

  <%= form.hidden_field( :status, :value => "approved")%>

  <div class="flex flex-col p-6">
    <div class="mb-4">
      <%=form.label "Email", class: "form-label"%>
      <%=form.text_field :email, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "First Name", class: "form-label"%>
      <%=form.text_field :fname, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "Middle Name", class: "form-label"%>
      <%=form.text_field :mname, class: "form-inputbox"%>
    </div>  
    
    <div class="mb-4">
      <%=form.label "Last Name", class: "form-label"%>
      <%=form.text_field :lname, class: "form-inputbox"%>
    </div>

    <div class="mb-4">
      <%=form.label "Contacts", class: "form-label"%>
      <%=form.text_field :contacts, class: "form-inputbox"%>
    </div>

    <div class="mb-8">
      <%=form.label "Address", class: "form-label"%>
      <%=form.text_field :address, class: "form-inputbox"%>
    </div>  

    <div class="flex items-center justify-between self-center mb-4">
      <%= form.submit "Create Account", class: "btn-primary" %>
    </div>
  </div>

<%end%>

app/views/admins/users/_orderlist.html.erb
<turbo-frame id="transaction_history" class="flex flex-col px-1 pb-4"></turbo-frame>

app/views/admins/users/_portfolio.html.erb
<div class="flex flex-col mb-4">
  <span class="text-white text-4xl font-bold mb-4">Stocks</span>
  <div class="flex items-center text-gray-500 mb-2">
    <div class="flex-1 w-[60px]"></div>
    <div class="flex-1 text-center min-w-[100px]">Code</div>
    <div class="flex-1 text-center min-w-[300px]">Name</div>
    <div class="flex-1 min-w-[100px]">On Hand</div>
    <div class="flex-1  min-w-[100px]">Price</div>
    <div class="flex-1 min-w-[100px]">Percentage Change</div>
    
  </div>
    
  <div class="flex flex-col">
    <% portfolio.each do | item |%>
      <div class="flex mb-2 text-white">
        <div class="flex-1">
          <img src=<%= item["logo"]%> class="w-[60px] h-[60px] select-none">
        </div>

        <div class="flex-1 min-w-[100px] text-center"><%=item["code"]%></div>
        <div class="flex-1 min-w-[300px]"><%=item["name"]%></div>
        <div class="flex-1 min-w-[100px]"><%=item["qty"]%></div>
        <div class="flex-1 min-w-[100px]"><%=item["latest_price"]%></div>
        <div class="flex-1 min-w-[100px]
          <%=item['change_percent'].to_f >= 0 ? 'text-green-500' : 'text-red-500'%>
        "><%=item["change_percent"]%>
        </div>
  
      </div>
    <%end%>
  </div>
</div>

app/views/admins/users/_searchbar.html.erb
<div class="searchbar">
  
  <%= form_with url: admin_user_search_path do |form| %>
    <%= form.search_field :user_search, oninput: "this.form.requestSubmit()",class: "h-[30px] min-w-[500px]" %>
    <button class="h-[30px] w-[40px] bg-slate-500"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
  <% end %>

  <span class="flex gap-2 text-white ml-auto justify-center items-center">
    <div class="bg-slate-500 bg-opacity-30 rounded-full px-2">
      <span><%=@current_user.email%></span>  
    </div>

    <div class="h-[30px] w-[30px] flex justify-center items-center rounded-full border-white border-[1px]">
      <i class="fa-solid fa-user "></i>
    </div>

    <div class="cursor-pointer">
      <i class="fa-solid fa-sort-down"></i>
    </div>
    
  </span>
</div>

app/views/admins/users/_show_user.html.erb
<div class="text-white mb-4">
  <div class="flex gap-4">
    <span class="text-gray-500">Name: </span>
    <div>
      <span><%= (user.fname).capitalize() %></span>
      <span><%= (user.mname).capitalize() %></span>
      <span><%= (user.lname).capitalize() %></span>
    </div>
  </div>

  <div class="flex gap-4">
    <span class="text-gray-500">Email:</span>
    <span><%= user.email %></span>
  </div>
</div>

<%= turbo_frame_tag "portfolio" do %>
<% end %>

<div>
  <%= render "admins/users/orderlist" %>
</div>

app/views/admins/users/_transaction.html.erb
<span class="text-white text-4xl font-bold mb-8">Order Lists</span>

<div class="flex gap-4 mb-2">
  <div class="bg-[#0b0f16] rounded-lg text-gray-500 text-xl items-center py-2 px-3">
    Transaction Filter
  </div>
  <%= form_with(scope: @user, url: admin_user_filter_order_path) do |form| %>
    <div class="flex gap-4 bg-[#0b0f16] rounded-lg text-gray-500 py-2 px-3 text-xl">
      <input type="hidden" id="user_id" name="user_id" value=<%= params[:user_id] %> />
      <%= form.submit "Buy" %>
      <%= form.submit "Sell" %>
      <%= form.submit "Deposit" %>
      <%= form.submit "All" %>
    </div>
  <% end %>
</div>


<div class="flex rounded-lg text-gray-500 text-lg mb-2">
    <span class="flex-1">Type</span>
     <span class="flex-1">Code</span>
     <span class="flex-1">Price</span>
     <span class="flex-1">Quantity</span>
     <span class="flex-1">Amount</span>
     <span class="flex-1">Transaction Date</span>
</div>
<% user_history.each do |data|%>
  <div class="flex bg-[#0b0f16] p-2 rounded-lg text-gray-500 text-lg hover:text-white
  transition-all duration-300 ease-in hover:ring hover:ring-[#03e9f4] mb-1
  ">
    <div class="flex-1">
      <%= data["kind"]%>
    </div class="flex-1">
    <div class="flex-1">
      <%= data["stock_code"]%>
    </div>
    <div class="flex-1">          
        <%= data['kind'] == "Deposit" ? nil : data["price"]%>   
    </div>
    <div class="flex-1">
      <%= data['kind'] == "Deposit" ? nil : data["qty"].abs()%>         
    </div>
    <div class="flex-1" style="width: 8rem;">
      <%= number_to_currency(data["amount"])%>
    </div>
    <div class="flex-1">
      <%= data["created_at"].strftime("%m/%d/%y")%>
    </div>
  </div>
<% end %>

app/views/admins/users/_userlist.html.erb
<%= turbo_frame_tag "searchbar" do %>
  <%= render partial: "admins/users/searchbar" %>
<% end %>

<div class="flex flex-col justify-center items-center mb-6">
  <span class="text-white text-5xl font-bold">Stock App Page</span>
</div>

<%= turbo_frame_tag "usertable", class: "flex flex-col" do %>
  <%= render partial: "admins/users/usertable" %>
<% end %>

app/views/admins/users/_users.html.erb
<%= turbo_frame_tag "ud#{user.id}" do %>
<div class="user-list">
  <span class="text-white mx-2">
    <%= user.id %>
  </span>
  
  <span class="flex text-white min-w-[250px]">
    <div class="h-[25px] w-[25px] flex justify-center items-center rounded-full border-white border-[1px]">
      <i class="fa-solid fa-user "></i>
    </div>
    <div class="ml-2">
      <%= user.lname %>, <%= user.fname %> <%= user.mname %>
    </div>
  </span>
  
  <span class="flex-1 text-white">
    <%= user.email %>
  </span>
  
  <span class="text-white flex-1 w-[100px] ">
    <%= user.status %>
  </span>

  <span class="flex-1 w-[100px] text-white">
    <%= user.created_at %>
  </span>

  <div class="flex gap-4 ml-2 ">
    <%= button_to "view", admin_user_show_path(email: user.email, user_id: user.id), class: "text-white" %>

    <%= button_to "edit", edit_user_path(email: user.email), 
    class: "text-white" %>

    <%= button_to "approve", activate_user_path(email: user.email) , :disabled => user.status === "approved", class: "text-white disabled:opacity-50 disabled:line-through" %>
  </div>
</div>
<% end %>

app/views/admins/users/_usertable.html.erb
  <div>
    <div class="table-header">
      <span class="mx-2"></span>
      <span class="min-w-[250px]">Name</span>
      <span class="flex-1">Email</span>
      <span class="flex-1">Status</span>
      <span class="flex-1">Date</span>
      <span class="text-center w-[155px]">Action</span>
    </div>

    <% @user.each_with_index do |user, index|%>
      <%= render "admins/users/users", user: user, index: index %>
    <% end %>
  </div>