config/routes.rb
Rails.application.routes.draw do
  root "traders#index"

  # Session routes
  get "/signin" => "sessions#signin", as: :signin_page
  get "/signup" => "sessions#signup", as: :signup_page
  get "/userinfo" => "sessions#userinfo", as: :userinfo
  post "/signin" => "sessions#new_session", as: :new_session
  post "/signup" => "sessions#new_account", as: :new_account
  post "/userinfo" => "sessions#new_userinfo", as: :new_userinfo
  post "/signout" => "sessions#signout", as: :signout

  # Admin Dashboard
  get "/admin" => "admins#index"
  # --Pages
  post "/admin" => "admins#homepage"
  post "/admin/userpage" => "admins#userpage"
  # --- Users
  post "/admin/user" => "admins#edit_user", as: :edit_user
  patch "/admin/user" => "admins#update_user", as: :update_user
  post "/admin/user/show" => "admins#show_user"
  post "/admin/user/new" => "admins#new_user", as: :new_user
  post "/admin/user/create" => "admins#create_user", as: :create_user
  post "/admin/user/activate" => "admins#activate_user", as: :activate_user
  post "/admin/user/search" => "admins#search_user"
  # ---- Users View
  post "/admin/user/waiting" => "admins#waiting_list"
  post "/admin/user/active" => "admins#active_users"
  post "/admin/user/filter_order" => "admins#filter_order"

  # Trader Homepage
  get "/home" => "traders#index"
  get "/pending" => "traders#pending", as: :pending_page
  # -- Pages
  get "/deposit" => "traders#deposit"
  get "/buy-sell" => "traders#buysell"
  get "/market" => "traders#market"
  get "/profile" => "traders#profile"
  get "/transaction" => "traders#transaction"
  # --- btn actions
  post "/deposit/addbalance" => "traders#add_balance"
  post "/buy-sell" => "traders#user_buysell"
  post "/transaction" => "traders#filter_transaction"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def initialize_stocks_master
    if ($stocks_master.blank?)
      file = File.read('./app/helpers/stock_master.json')
      $stocks_master = JSON.parse(file)
    end
  end
  
  def current_user
    token = session[:gen_token]

    if token.present?
      user = Authentication.find_by(token: token)
      user.user
    end
  end

  def require_user
    token = session[:gen_token]
    
    if token.present?
      user ||= Authentication.find_by(token: token)
    end    
    redirect_to "/signin" unless user
  end

  def require_admin
    admin ||= session[:is_admin]
    redirect_to "/admin" unless admin
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_logo(stock_symbol)
    if newarray = $stocks_master.find { |item| item['symbol'] == stock_symbol }
      if newarray['url']
        newarray['url']
      else
        newarray['url'] = IEX_CLIENT.logo(stock_symbol)['url']
        $stocks_master.find { |item| item['symbol'] == stock_symbol ? item.replace(newarray) : '' }
        File.write('./app/helpers/stock_master.json', JSON.dump($stocks_master))
        newarray['url']
      end
    end
  end

  def check_quote(stock_symbol)
    if newarray = $stocks_master.find { |item| item['symbol'] == stock_symbol }
      if newarray['quote']
        newarray['quote']
      else
        newarray['quote'] = IEX_CLIENT.quote(stock_symbol)
        $stocks_master.find { |item| item['symbol'] == stock_symbol ? item.replace(newarray) : '' }
        File.write('./app/helpers/stock_master.json', JSON.dump($stocks_master))
        newarray['quote']
      end
    end
  end

end

app/views/application/_header.html.erb
<div class="nav-bar">
  <div class="nav-items">
    <a href="/stocks/show">Stocks</a>
  </div>
</div>

app/views/application/_navbar.html.erb
<div id="navbar" class="flex py-4 px-8 gap-4 bg-[#0b0f16] items-center">
  
  <%= link_to raw('<span class="text-2xl font-bold font-slant miami font-outline-1 select-none">MiamiTrades</span>'), home_path %>  

  <div>
    <%= link_to raw('<span class="navtext">Stocks</span>'), buy_sell_path %>
  </div>

  <div>
    <%= link_to raw('<span class="navtext">Markets</span>'), market_path %>
  </div>

  <div class="flex gap-4 ml-auto items-center">
    <div>
      <%= link_to raw('<span class="navtext">Profile</span>'), profile_path %>
    </div>

    <div>
      <%= link_to raw('<span class="navtext">Wallet</span>'), deposit_path %>
    </div>

    <div>
      <%= link_to raw('<span class="navtext">Orders</span>'), transaction_path %>
    </div>

    <span class="bg-white h-[20px] w-[1px]"></span>
    <%= button_to "Logout", signout_path, data: { turbo: true }, class: "text-[#f890e7] hover:text-[#03e9f4] transition duration-300 ease-in" %>
  </div>
</div>